
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/bank_system


service.bank2.url=http://bank-system2:8091
service.fast.url=http://fast-system:8088
service.civil.url=http://civil-system:8086