package Finance.Bank_System.business.abstracts.individualCustomer;

import Finance.Bank_System.business.requests.İndividualCustomer.CreateİndividualCustomerRequest;
import Finance.Bank_System.business.responses.İndividualCustomer.AfterCreateİndividualCustomerResponse;

public interface İndividualCustomerService {
	
	 AfterCreateİndividualCustomerResponse createİndividualCustomer(CreateİndividualCustomerRequest createİndividualCustomerRequest);

}
